# Generated by Django 4.1 on 2022-09-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
