# Generated by Django 4.1 on 2022-09-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('key', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=255, unique=True)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
