# Generated by Django 4.1 on 2022-09-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
